# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:T5/1RN8=,iv:WQauaL1jZv0v7aIgFQzq68jS3brsXwAWpEWFbNiM3U4=,tag:5ZsfDCBA0Z/8zNcdEk3Eug==,type:str]
    admin-password: ENC[AES256_GCM,data:1e5W2BXzrbqwVw==,iv:B2GG/Ka9b4cO/MqeqDSVK+UUILwXnxASH8FSx18q7pk=,tag:MRneA1N3MHzQY6HYdLPBZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOWV3Z0crdjJuME5aSzV3
            aS9iQktGbEllVjM0RUZrSmpxVE4rWWcvNlJnCjc1eEdGaXdCMnowbW1TK2svNU5m
            Yk8yZGszZk00K0kzN1FyTGhvVjRCbTQKLS0tIGNWM08zdHFldWprSnN1VHJPTzdi
            K3ZtYnRqYmpRMnowenZ2d0ttdFF5NEkKJfvtpZNOLzARPnLuZED5nltqj+Hyeq8C
            J8hxDh16Oqqo3lyXfK6q+fyXvPPESnhK6gYVgJyHGl2gQbQUmfJiEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T12:18:02Z"
    mac: ENC[AES256_GCM,data:2TiIiC67p49GbG1HYczi3+XkbIYUnJpjXNHIzd5o6ltp3kmY1EgCr+P2YmZCC699/kareUGJ6mZl4lYQJ1xtiOK1OMd/8YsU9X3JTK+LxGRwIAa5FvFW4YVejNlPW7i2Pa5gONKGkUdcYPgViDQm+NHIDLe+HKylB194V5XMSxY=,iv:oUEL9jyOXW6nAseQYAe6IQ/Fo/nrDa6PFLsEQi27cm0=,tag:Jk4NPWsX9IW222kQxfrhog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:hgtirTZUPQ==,iv:4Z09hadQ5KbKYTPZeTWY0JEwlvGATs1bxYkLxLgOD6A=,tag:sU/3cJEFyRSqPj0WZmtCzw==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:vacl447gJJfTPNyUmxodF0IMaM0=,iv:buBbehSk1TaY3IrtkQ+NxH5X6nDDkp4SqD8OEd7aY7Y=,tag:bPGOn5VdeJ7F9/sSW+NnYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOWV3Z0crdjJuME5aSzV3
            aS9iQktGbEllVjM0RUZrSmpxVE4rWWcvNlJnCjc1eEdGaXdCMnowbW1TK2svNU5m
            Yk8yZGszZk00K0kzN1FyTGhvVjRCbTQKLS0tIGNWM08zdHFldWprSnN1VHJPTzdi
            K3ZtYnRqYmpRMnowenZ2d0ttdFF5NEkKJfvtpZNOLzARPnLuZED5nltqj+Hyeq8C
            J8hxDh16Oqqo3lyXfK6q+fyXvPPESnhK6gYVgJyHGl2gQbQUmfJiEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T12:18:02Z"
    mac: ENC[AES256_GCM,data:2TiIiC67p49GbG1HYczi3+XkbIYUnJpjXNHIzd5o6ltp3kmY1EgCr+P2YmZCC699/kareUGJ6mZl4lYQJ1xtiOK1OMd/8YsU9X3JTK+LxGRwIAa5FvFW4YVejNlPW7i2Pa5gONKGkUdcYPgViDQm+NHIDLe+HKylB194V5XMSxY=,iv:oUEL9jyOXW6nAseQYAe6IQ/Fo/nrDa6PFLsEQi27cm0=,tag:Jk4NPWsX9IW222kQxfrhog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
