# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:nUgnb5eyqdvvwyqzhiE2tDdZrA==,iv:j/GZ1rowRY9das2yUKPUcEO6koKONoGs2SFwvmKzpIs=,tag:Yo3iHFH/Ge6yAhsrJIdtAA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:5fzXHRmp9BrlnH1vovJNPUZAXIc=,iv:cr9rCTy9gAPwaldYHgCpS5yPgEPSMqcsf7ZXcdMFXMk=,tag:OTvJkL2Cx3yZrtnSBlgy0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWW9QUE5qMzVDNGhOb29w
            YWhhNzNqaXdzWUc1MTloZVdjZlRkSkpCblJBCjA4Ukd6WmJLY21rK3lNcW5zaDVx
            aXZpQ0ZicGNodlNFR2lyUENyd0FzQkUKLS0tIFVvSURtSmdsREJPWDNQKzM1T2RN
            d1doU0QxQmxIbC9QK3k3K2x3RmloVHMKjpg+WTtidyjvMTByn4uWW4jkWKRiq9LK
            MuJBTtiKLNtdn25rAreYnf++u+arSfrVBqKscZTbIlCFCFX6ZW/CkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-11T11:31:22Z"
    mac: ENC[AES256_GCM,data:isZ7Btn8rDPmK+mJtAaMHjYRUdDQrZNN7IBLqlHE12TqmFLd9tzrvXl/taTZIrARMiIATTLitW75X1KyypszIJtMyi6cytECLcHSpR0odpp8fB4T4RGck+ldcr9RQwkZas7OmiO7PaloEqqeDGw3DXyLVS0Vxlhn85XgoqD6dLs=,iv:1VZhLGC/BBa+Sjh2II6sR/PJ4oNSn5h4KZDWdQW6jkw=,tag:l+AD9KXC4mVqRVIo0NcosA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
