# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: loki-s3
    namespace: monitoring
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/yGCeSBLTn28D5nGRBrL,iv:4lfwEGkdPUFmcmmH1fGcpSDyitu/uYFWCYZmJAaAiHM=,tag:uuAxhJ/xt0gEostSncUBqw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Xc8zeR3aOhJ8U9ZUl8TAQK0EIA==,iv:s4HUQA6We1+Z1nPJHu+xMoCTOknCfixmxY5ieIfrNws=,tag:wosaUt7JAALgwM9GNPfKlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbno0bGQvSlhVbndEcGJS
            T1VOSFkrSmVzaHZBRm9xaHNOYS9mR2dkNlhRCmF0dVV3V0dUeEJSbVlJMVI4QXBU
            N0J4ajhwVENzUFdmZHY3OTY0aTU1QmcKLS0tIEE4dkFOTk0rOGpxYldLWmZIVmEx
            UllRYlhKWWszSlUzdTBjVklWeitlaWMKlnmFiq0sJ1eRTLFs3lexWdThnUUDd8eL
            8F7NDebNTEfRFU6zUGXFPekqKRUwux4AP+NWi9+REMB4MRQ4jqwlYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T13:16:24Z"
    mac: ENC[AES256_GCM,data:OIcqrcao5tZjfH/uO40GkJeJcGLI8hPmWTe9mElMD0NuLuO+tG7AJU3WHyf0xPmVIqEzQLN4CkdtJtiUeXKdqo6R1Q9I2/YOLkdGGIzkjPJaaYn9eIlHFOB07v/ynCSoFhqm5ijMl66VhiMbPHaiDm70lgxZ9P3n/7IuE++dkTY=,iv:1C3IwIXcXSmyn/hGYvpy3tbXWawnGt0fP665WZQLUzI=,tag:xlLpkXrsFebWxdR9MnSbMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
