---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: splunk-operator-app-download
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
