---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-charts.yaml
  - bjw-s-charts.yaml
  - cloudnative-pg-charts.yaml
  - csi-driver-nfs-charts.yaml
  - descheduler-charts.yaml
  - dysnix-charts.yaml
  - external-dns-charts.yaml
  - grafana-charts.yaml
  - hajimari-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - kubereboot-charts.yaml
  - kubernetes-dashboard-charts.yaml
  - k8s-gateway-charts.yaml
  - kyverno-charts.yaml
  - longhorn-charts.yaml
  - longhorn-git.yaml
  - node-feature-discovery-charts.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - prometheus-community-charts.yaml
  - stakater-charts.yaml
