---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app flaresolverr
  namespace: media-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/flaresolverr/flaresolverr
      tag: v2.2.10@sha256:08cf762f3f538438c949c5ec63dd9ed99a9c8de7745f50378ac6a358604f5023
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 8191
