---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prowlarr
  - radarr-hd
  - radarr-uhd
  - sonarr
  - sonarr-uhd
  - unpackerr-hd
  - unpackerr-uhd
