---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-automation
resources:
  - secret.sops.yaml
  - helm-release.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
