# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kJGA8q3oNVE9uw0=,iv:6GlBN6xmu+Hqlc0MVJXcsFVXcq7gm44Mf05vt7k/EhE=,tag:8qVMuS1ZmpJABIgVkm9qTw==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:kAJ7jsB4G9HZuA+X,iv:eHP3/dbwSKrVyfF7+r3rQMBacbBnZNTE3nQ9DFO3bgo=,tag:DtEGmrKTmQsmEThqTtX2CA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:UaLVAsz73K3wyVchoE8JdnmMJj8=,iv:uQx/eqSqrOVurrnoEk/q0ho0CPlKdDH1WzuYK8Ikiqw=,tag:zoo3/FRfdYeBjZBz7+f5Vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QnBPSjFCZW1XZnhVdkhk
            SG1jWUVFdXNaOUt4NmkwYWZ4K1p0clY3dkVVCitYeWNoUUVjbUJFczY2OG1TYU1Z
            VSt2UHcya0xCNFBjeDU1RW5nNGhBdlkKLS0tIHA5VmZBenJxVlpRUFNEbEJSM0ly
            WUluME9HTnBlamhoaUN1TDQ3eEcvV1kK/YFRT9mVPDwQqYgnSxR1aN6ufNlnkauT
            B/1NiCfJMKw4TsnArz1F36k9xvPBhyM4Fe0ZhcCGe7QOM4ZmYMqo7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-10T12:47:59Z"
    mac: ENC[AES256_GCM,data:1Mr0amIhfF52XjQ33OzBRDuK5PDo/UF6+542zkycdALeQAWkH6XOBl9zAwZoVwbAHLCm8Ah9g4M7q3M8nHS1AVf0DZj+04MOiM3JbDPMeb//d2F50SORnZLqAST7mw1G6ut7S+68J78fdbtXunLJKvdVC5pcjpXUWSmCXaGGsM0=,iv:PGimZncK3ii+nyBCEWw8djGxe8VicZe+DnABO4agKU8=,tag:Qww3BAquUK16P9EWwpt2vQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
