# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr-uhd
    namespace: media-automation
type: Opaque
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:IBvwxeFMhF70HG8XXW+4dS2c+DwPGtXglADapcpqNCE=,iv:Wcv2b0HuuyzkyIK6mocaFYlwrpx7IchxEucKMRKX9FY=,tag:eTTj4cAiEML8HjHp4D+epg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWlF0TUJvbGo3bUNDMnl0
            TUJZTTFPb0RkVnhhSWpIeVRnaDFoWHV4SkVFCjRzUDVWMGRFak9rUUFqalhLSzZW
            ZGlJU0ZMMWRSQ0hoaUQzSldOWDdqa1UKLS0tIHlnV0Z0Zy8zVTU0dVRiMC9Laktj
            R2VSUVhOUW9SODkrRzEyblo2WVZJdlkK3lXClQvlcrbjYU9WCvJ4f0Zrt1K1goyG
            QhdgtLt3gAXAN0cz5HWJK/qLLXoaTy3Y4Iz8Oxx33W01+V7WBzF7eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-21T11:38:29Z"
    mac: ENC[AES256_GCM,data:2g7xj2gUe/7rwtVWwyb3omzMO5h4fAfPFwNE3rMF8Jm9FXXu6Wo8KA04aql1RlaB6KVWH4kDP1vd86TZsGxxKRRX1iXOU6Hjqi6AlW4TgUOhRicqSiyqICd78xZreBOM/EEJincwzIO4OSgsM85sYtvJ+1iGh3ulY3AALWijVgo=,iv:c68/ZiF+GZlc3ZCRPb9wlqqGjv6IT3TcPsrMl3vDiis=,tag:9zBAw3igYEb1EcYpMVILVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
