---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app unpackerr-uhd
  namespace: media-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/onedr0p/unpackerr
      tag: 0.10.1@sha256:1382d6094df6ac9f7c5938158d414ccaf32186ee19824d450144829824927ce0
    env:
      TZ: "${TIMEZONE}"
      UN_RADARR_0_URL: http://radarr-uhd.media-automation.svc.cluster.local
      UN_RADARR_0_PATHS_0: /complete/radarr-uhd
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      fsGroup: 0
    persistence:
      complete:
        enabled: true
        type: nfs
        server: "scorpion.${SECRET_PRIVATE_DOMAIN}"
        path: /volume1/data/media/downloads/complete
        mountPath: /complete
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 1000Mi
