# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: unpackerr-uhd
    namespace: media-automation
stringData:
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:URI9FQwrhzkbK/EQHnqlq9J+1/srLEpPHHvW8DPRafY=,iv:cQPt34EKEBgxSjfO46A29cOqh160ZfnSQpJ1cUNvZiE=,tag:njLs4KgZypZ5V9ryDvh/zg==,type:str]
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:Q/ExtU50Sbzmk6+OC+/P68+76NJZ+lXj1Dl5KdxbA7A=,iv:Moq5Xg5sNFXsnlP4+D+aB3+i/IL50TDrpdbCZIEDxTg=,tag:2hQLDXZ95ytyTCdZtA25Vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUk9ZTitvRHdqY1pvd216
            ajdhR0xoQ0kxZVlwSUg3RkxaSCszQzByWFFnClVWcUs5cExhT0NuNXhUR1JBdUgr
            UFBTNmZtUUcwNlBTZWM1YWJWalhMMkEKLS0tIEVXSjVULzNLV1Q1UFFtc01oT0kw
            S3E0Q254a0RhOVpFcDNDNG11eXBUY0UKg98/W0FQYOmJtfkxChnTAUWsManUDseg
            mr2eZ1RQ3VOEP5M9ag9JhDQeSJ4QEazkF54qdmOPDJhErMxg/HRPwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-11T12:58:19Z"
    mac: ENC[AES256_GCM,data:w5yuWTRfpxhYPBgnHpb2hCKgk2kA0xXZ0TjN//1srpZlIl+GUybpORHWF6UM4Hd5rYmluRY9yMbXrYwFcSYGE+qA/37FtOIaYQC0zDTWLDmUPnw0BSCKhuU3Efk1Oa7HFUqbMpmw/LftrwSQS1c5N4yADBHCHvdPkc4SKa98Pj0=,iv:7/+iP8rhWeoBlNIzxjCVeuhBg6G5cgXfURt+JybTZ8E=,tag:a4W21fP2JpsYsyXBSsHtHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
