---
session:
  redis:
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.databases.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.databases.svc.cluster.local
          port: 26379
        - host: redis-node-2.redis-headless.databases.svc.cluster.local
          port: 26379

access_control:
  default_policy: deny
  rules:
    - domain: ["grafana.${SECRET_DOMAIN}"]
      policy: bypass
    - domain: "*.${SECRET_DOMAIN}"
      policy: bypass
      networks:
        - 10.0.0.0/8
    - domain: "*.${SECRET_DOMAIN}"
      policy: two_factor

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret: "${SECRET_GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.${SECRET_DOMAIN}/login/generic_oauth"]
        userinfo_signing_algorithm: none
    #   - id: outline
    #     description: Outline
    #     secret: "${SECRET_OUTLINE_OAUTH_CLIENT_SECRET}"
    #     public: false
    #     authorization_policy: two_factor
    #     pre_configured_consent_duration: 1y
    #     scopes: ["openid", "profile", "email", "offline_access"]
    #     redirect_uris: ["https://docs.${SECRET_DOMAIN}/auth/oidc.callback"]
    #     userinfo_signing_algorithm: none
