# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-uhd
    namespace: media-automation
type: Opaque
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:NOQSUXw2GuWij2v82yw9I0kL5FJwL6B3Wd31KVrjys1q,iv:SGlL5smRFpIY+zbZdvavSmPJsA0UkMnjvKebeAn8J8E=,tag:w4VT0hDVwzNOLBBA05b81w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaFJiSHFBT2M2cDdvUjVB
            NXQ0aHREZ2R1dDNwNmR3bUh5TnBSTkEzbTBRCk9qbDIxcWg4azhsRG51WXJjZlZL
            eFBITHlDbDBaNnBzRG5qbXdBUjFiS1kKLS0tIFpNQ2xKNGdjNXAzMzlOeThFT2xJ
            SnZ6ZmU5SHp1ZTFzZFVBczRTRzFIbDAK6Fxfv4PIcHruc57LtJZr1Jkfj8rVsFj3
            HX7MauaKZ54igOQhKwUdcxoXyFvt2/onsjziSgmHgJ7EeaADxLlwaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-11T12:30:32Z"
    mac: ENC[AES256_GCM,data:YW4bVIkcP+pJqxriceBR3L1YwdVKXOf66jbFFOiIi0x67XH4RN0jMsOgz7DK8b1S/KSkTNdWCNf2L1svgSfOclPFvH9sedRQrCG1v3RSQ745kvXPDn1NOfz20n/OXRQHFgRMpgmvWjS94tHkjTyN3846CU9bL7ZqtY4aF1fnnTM=,iv:FintzXD6Nu0tDtaelbAjC9/Faofuf4ArDGEvJROnhHs=,tag:HX44HZwsfK72UcB3T/Tr8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
