---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  values:
    extraInitContainers:
      - name: init-db
        image: ghcr.io/onedr0p/postgres-initdb:14.5@sha256:497c88acc613d671c666be536b0bd0a4fc2f3a64aa275d54b79af8c446e20433
        env:
          - name: POSTGRES_HOST
            value: postgres-rw.databases.svc.cluster.local
          - name: POSTGRES_DB
            value: grafana
          - name: POSTGRES_SUPER_USER
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: username
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: grafana
                key: GF_DATABASE_USER
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: grafana
                key: GF_DATABASE_PASSWORD
