---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  values:
    extraInitContainers:
      - name: init-db
        image: ghcr.io/onedr0p/postgres-initdb:14.7@sha256:63d3321053b2033bd5dff909959513939795f7ec7d66b473b457f933325c4c5a
        env:
          - name: POSTGRES_HOST
            value: postgres-rw.databases.svc.cluster.local
          - name: POSTGRES_DB
            value: grafana
          - name: POSTGRES_SUPER_USER
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: username
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: grafana
                key: GF_DATABASE_USER
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: grafana
                key: GF_DATABASE_PASSWORD
