---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app redis
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 17.4.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # dependsOn:
  #   - name: longhorn
  #     namespace: longhorn-system
  values:
    global:
      imageRegistry: public.ecr.aws
      storageClass: longhorn
    auth:
      enabled: false
      sentinel: false
      # existingSecret: *app
    sentinel:
      enabled: true
      masterSet: redis-master
      getMasterTimeout: 10
      startupProbe:
        failureThreshold: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
