# yamllint disable
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:zXKJCL1oj3U=,iv:/0iKK0Nucc+qrfhu8X0oiNyPq9TGnffO+ARnowf/m90=,tag:/UDdSIdwhOjlWh8CEG1c5w==,type:str]
    password: ENC[AES256_GCM,data:37AvaZO6wyi62PFqfIbakyX6pLQ=,iv:gAkgRBV8TrWdO0S2cjIyFexaX5zKkR60mUExCvpw6K8=,tag:N0hGwk2cGRsFXGTHMfdk2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMEd2ZG5jSjhuWVJINVJI
            Ung1Y2JVYWNXUnlkL3JaZ01KZzRTQkFsbDM4CjZlOGxCNHlrTEJUbjBtaVV6NURr
            RjU2cnQ5dTBPZ3lHbVc2SVhxZklpaFEKLS0tIEJtSCsyWlQ0anJaSS9sUklFVHB5
            Z0wvWGRaSEpMZmZ3TDlYMEVhUml1Nm8KjPePqr5Ht56wxoIB0ZQA/A+MskvpLN7K
            TMpdOyEDtZcJK1CP03RZfQgueC03lwO2z5UoJFCr4wtHv6eA8Xf7OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-14T12:49:47Z"
    mac: ENC[AES256_GCM,data:Y7SWD51Day8ZEVSmU13ac/3adjLk/Sn4lokhjeJLlrFodlkdhrKHzSLf+/I27p4hpk+wpacX7gUx49KIyhu0GcwVrLKUw6th6sQwwP0ivPJiG2RLAEoOWnpb+4glbne1V1Q/7kpmLCsv25Xr/cfzMQ5HdUNjigiSc6DgC8qodBc=,iv:VYJkCwzgtsvDfF5lT4qhQZFVsSU3i6QBrgqzNWgThFs=,tag:x719f4LTqyhat5YhofWZfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:1GQOolKqDe0=,iv:vmi+RVFq/dtQz0fWuJ8cPssKuL8zixTfG9brQPMuS50=,tag:GIkLJkt8AW76oV8zADbBVg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:fliTR25rWgP/pCYksDQRDINnxCw=,iv:CpK+jSr7AF5cG4f16TjqCefekIayK73+e3jPnqPxGu4=,tag:Z5t1TL5rAHqXANHBn1fSUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMEd2ZG5jSjhuWVJINVJI
            Ung1Y2JVYWNXUnlkL3JaZ01KZzRTQkFsbDM4CjZlOGxCNHlrTEJUbjBtaVV6NURr
            RjU2cnQ5dTBPZ3lHbVc2SVhxZklpaFEKLS0tIEJtSCsyWlQ0anJaSS9sUklFVHB5
            Z0wvWGRaSEpMZmZ3TDlYMEVhUml1Nm8KjPePqr5Ht56wxoIB0ZQA/A+MskvpLN7K
            TMpdOyEDtZcJK1CP03RZfQgueC03lwO2z5UoJFCr4wtHv6eA8Xf7OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-14T12:49:47Z"
    mac: ENC[AES256_GCM,data:Y7SWD51Day8ZEVSmU13ac/3adjLk/Sn4lokhjeJLlrFodlkdhrKHzSLf+/I27p4hpk+wpacX7gUx49KIyhu0GcwVrLKUw6th6sQwwP0ivPJiG2RLAEoOWnpb+4glbne1V1Q/7kpmLCsv25Xr/cfzMQ5HdUNjigiSc6DgC8qodBc=,iv:VYJkCwzgtsvDfF5lT4qhQZFVsSU3i6QBrgqzNWgThFs=,tag:x719f4LTqyhat5YhofWZfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
