# yamllint disable
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:zXKJCL1oj3U=,iv:/0iKK0Nucc+qrfhu8X0oiNyPq9TGnffO+ARnowf/m90=,tag:/UDdSIdwhOjlWh8CEG1c5w==,type:str]
    password: ENC[AES256_GCM,data:37AvaZO6wyi62PFqfIbakyX6pLQ=,iv:gAkgRBV8TrWdO0S2cjIyFexaX5zKkR60mUExCvpw6K8=,tag:N0hGwk2cGRsFXGTHMfdk2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMEd2ZG5jSjhuWVJINVJI
            Ung1Y2JVYWNXUnlkL3JaZ01KZzRTQkFsbDM4CjZlOGxCNHlrTEJUbjBtaVV6NURr
            RjU2cnQ5dTBPZ3lHbVc2SVhxZklpaFEKLS0tIEJtSCsyWlQ0anJaSS9sUklFVHB5
            Z0wvWGRaSEpMZmZ3TDlYMEVhUml1Nm8KjPePqr5Ht56wxoIB0ZQA/A+MskvpLN7K
            TMpdOyEDtZcJK1CP03RZfQgueC03lwO2z5UoJFCr4wtHv6eA8Xf7OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-11T11:29:57Z"
    mac: ENC[AES256_GCM,data:/KdgM18YwD1Fvr63SdU6V1HBFds0jF4W9G0c+fh/AfSpxGkokmSK/Z9YLTCTs0Z4/wqgQ8ohqFx32xAVy1TJV7/SwE/UIeBaz1Z6+9T0DE0Ct+dVAtpzm1dp1ieAyxp4xTBPqRpo0Vji1UhiCk8gXh1a9KBBq4Js+Q7PIV99n/8=,iv:4x6Fcwnks4BrQrraLxCRCy6yikFum6A5cHGrqFoebb4=,tag:lPRBjvrvEf4KH+OdHsAutA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
