---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart/
      version: 1.4.0-dev
      sourceRef:
        kind: GitRepository
        name: longhorn-git
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    persistence:
      defaultClass: true
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns.home.arpa/enabled: "true"
        hajimari.io/enable: "true"
        hajimari.io/appName: "Longhorn"
        hajimari.io/icon: "database"
      host: "longhorn.${SECRET_DOMAIN}"
      path: /
      tls: true
      secureBackends: true
      tlsSecret: "longhorn-tls"
    enablePSP: false
