---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart/
      version: 1.4.0-dev
      sourceRef:
        kind: GitRepository
        name: longhorn-git
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      longhorn:
        engine:
          repository: longhornio/longhorn-engine
          tag: v1.4.x-head
        manager:
          repository: longhornio/longhorn-manager
          tag: v1.4.x-head
        ui:
          repository: longhornio/longhorn-ui
          tag: v1.4.x-head
        instanceManager:
          repository: longhornio/longhorn-instance-manager
          tag: v1.4.x-head
        shareManager:
          repository: longhornio/longhorn-share-manager
          tag: v1.4.x-head
        backingImageManager:
          repository: longhornio/backing-image-manager
          tag: v1.4.x-head
        supportBundleKit:
          repository: longhornio/support-bundle-kit
          tag: v0.0.17
      csi:
        attacher:
          repository: longhornio/csi-attacher
          tag: v3.4.0
        provisioner:
          repository: longhornio/csi-provisioner
          tag: v2.1.2
        nodeDriverRegistrar:
          repository: longhornio/csi-node-driver-registrar
          tag: v2.5.0
        resizer:
          repository: longhornio/csi-resizer
          tag: v1.3.0
        snapshotter:
          repository: longhornio/csi-snapshotter
          tag: v6.0.1
        livenessProbe:
          repository: longhornio/livenessprobe
          tag: v2.8.0
      pullPolicy: IfNotPresent
    persistence:
      defaultClass: true
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns.home.arpa/enabled: "true"
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hajimari.io/enable: "true"
        hajimari.io/appName: "Longhorn"
        hajimari.io/icon: "database"
      host: "longhorn.${SECRET_DOMAIN}"
      path: /
      tls: true
      secureBackends: true
      tlsSecret: "longhorn-tls"
    enablePSP: false
