---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app unpackerr-hd
  namespace: media-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/unpackerr
      tag: 0.10.1@sha256:9daddbc32e93777bde6dfc45d088021b8a53bcb717f38508259641a5e11aa27f
    env:
      TZ: "${TIMEZONE}"
      UN_SONARR_0_URL: http://sonarr.media-automation.svc.cluster.local
      UN_SONARR_0_PATHS_0: /complete/sonarr
      UN_RADARR_0_URL: http://radarr-hd.media-automation.svc.cluster.local
      UN_RADARR_0_PATHS_0: /complete/radarr-hd
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      fsGroup: 0
    persistence:
      complete:
        enabled: true
        type: nfs
        server: "scorpion.${SECRET_PRIVATE_DOMAIN}"
        path: /volume1/data/downloads/complete
        mountPath: /complete
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 1000Mi
