# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: unpackerr-hd
    namespace: media-automation
stringData:
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:u+ZrXOvvqHXKWVUiOitspHf7FtG1euPBoyH260PyirQ=,iv:cINE31Mig4q7nJKtrxoYhoZkLhdOcAhQakhKpDrM4Wc=,tag:Bob+wehBuCIBgQ5JyUvP4w==,type:str]
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:7+eLnW+/r+jsbZ5gKEX98kkPFbZo84TNpVXLWQ2Cips=,iv:qF69wNVqN2gScgTdotsjiDu9moJ1D5Epp6q74RXsxww=,tag:XXstx6xw8qGdHhemrhjBcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUk9ZTitvRHdqY1pvd216
            ajdhR0xoQ0kxZVlwSUg3RkxaSCszQzByWFFnClVWcUs5cExhT0NuNXhUR1JBdUgr
            UFBTNmZtUUcwNlBTZWM1YWJWalhMMkEKLS0tIEVXSjVULzNLV1Q1UFFtc01oT0kw
            S3E0Q254a0RhOVpFcDNDNG11eXBUY0UKg98/W0FQYOmJtfkxChnTAUWsManUDseg
            mr2eZ1RQ3VOEP5M9ag9JhDQeSJ4QEazkF54qdmOPDJhErMxg/HRPwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-14T12:56:06Z"
    mac: ENC[AES256_GCM,data:F2iixLMV1snPxuLh/M/9U66D2TKuP4JSDJAyuLxoaI+Qej0VcpODqG1hY7jZhmhVaebRhTpMrqZEbT3UMexQahAPzA6rpRsOYdqnQAuZ2ikVqpi2jU0JMl1oGEWOKTogIdTEQadOxLSwUB+YDpm4V6CB1G12Ae8T+7ytFDkF+zA=,iv:IsUZvjeEyf7Pt+YrjI1oY97K9+u6KrFtJxSdQm+KSvk=,tag:SYG2VnZd/T3jRX9bnmCeeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
