---
apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  name: ds
  namespace: splunk-enterprise
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  startupProbe:
    initialDelaySeconds: 40
    timeoutSeconds: 30
    periodSeconds: 30
    failureThreshold: 20
  livenessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 30
    failureThreshold: 6
  readinessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    failureThreshold: 6
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2500m
      memory: 4096Mi
  volumes:
    - name: defaults
      configMap:
        name: splunk-ds-defaults
    - name: licenses
      configMap:
        name: splunk-licenses
  licenseUrl: /mnt/licenses/enterprise.lic
  defaultsUrl: /mnt/defaults/default.yml
  extraEnv:
    - name: SPLUNK_ROLE
      value: splunk_deployment_server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.org/client-body-buffer-size: 100M
    nginx.org/client-max-body-size: "0"
    nginx.org/server-snippets: |
      client_body_buffer_size 100m;
    nginx.org/ssl-services: splunk-standalone-standalone-headless
    external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
    external-dns.home.arpa/enabled: "true"
    hajimari.io/enable: "true"
    hajimari.io/appName: "Splunk-DS"
    hajimari.io/icon: "mdi:splunk"
  name: splunk-ds-ingress
  namespace: splunk-enterprise
spec:
  rules:
    - host: "deploy.${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: splunk-ds-standalone-service
                port:
                  number: 8000
            path: /en-US
            pathType: Prefix
          - backend:
              service:
                name: splunk-ds-standalone-service
                port:
                  number: 8089
            path: /.well-known
            pathType: Prefix
  tls:
    - hosts:
        - "deploy.${SECRET_DOMAIN}"
      secretName: splunk-ds-tls
