# yamllint disable
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:zXKJCL1oj3U=,iv:/0iKK0Nucc+qrfhu8X0oiNyPq9TGnffO+ARnowf/m90=,tag:/UDdSIdwhOjlWh8CEG1c5w==,type:str]
    password: ENC[AES256_GCM,data:37AvaZO6wyi62PFqfIbakyX6pLQ=,iv:gAkgRBV8TrWdO0S2cjIyFexaX5zKkR60mUExCvpw6K8=,tag:N0hGwk2cGRsFXGTHMfdk2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMEd2ZG5jSjhuWVJINVJI
            Ung1Y2JVYWNXUnlkL3JaZ01KZzRTQkFsbDM4CjZlOGxCNHlrTEJUbjBtaVV6NURr
            RjU2cnQ5dTBPZ3lHbVc2SVhxZklpaFEKLS0tIEJtSCsyWlQ0anJaSS9sUklFVHB5
            Z0wvWGRaSEpMZmZ3TDlYMEVhUml1Nm8KjPePqr5Ht56wxoIB0ZQA/A+MskvpLN7K
            TMpdOyEDtZcJK1CP03RZfQgueC03lwO2z5UoJFCr4wtHv6eA8Xf7OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-16T10:56:59Z"
    mac: ENC[AES256_GCM,data:L2JeNgEuxxYV7FpR0L1vKWU4ShKnarPZfdDq3Jq6Dq3c3xlC2okQHXZn/hctEq8cahurng0CkLbZCp+9VrPGNO8NcMaFS4Jo6r7OJ7bWgdhbVfTaTmeJek/dJnTPIZebWPzd5iY9sZR4/wgWia0EDAgKFaHF6W0zz8voborn1UY=,iv:tDSgjnqy2UjoKuyfQJLwNY44ApUrUT1RdR2V1FpY6HY=,tag:mh7WX3uxtkrupLK5CjL/JA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:QIKTxlWBC+U=,iv:Uk6e7tMMsH+U8bNrBikwg9K+lY3jVNRZQwlEo8ek9OU=,tag:rj0Vjad1QH+3KQkAlb+k4g==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:iZhSLYFJjU5eDPbqxruWJFmz8A==,iv:CHko6fHZlmXiXhB9NTBZVWftxPjcGGQbe+IA/+wWgig=,tag:rIfxAXhMyRzDIwZUoE4P8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMEd2ZG5jSjhuWVJINVJI
            Ung1Y2JVYWNXUnlkL3JaZ01KZzRTQkFsbDM4CjZlOGxCNHlrTEJUbjBtaVV6NURr
            RjU2cnQ5dTBPZ3lHbVc2SVhxZklpaFEKLS0tIEJtSCsyWlQ0anJaSS9sUklFVHB5
            Z0wvWGRaSEpMZmZ3TDlYMEVhUml1Nm8KjPePqr5Ht56wxoIB0ZQA/A+MskvpLN7K
            TMpdOyEDtZcJK1CP03RZfQgueC03lwO2z5UoJFCr4wtHv6eA8Xf7OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-16T10:56:59Z"
    mac: ENC[AES256_GCM,data:L2JeNgEuxxYV7FpR0L1vKWU4ShKnarPZfdDq3Jq6Dq3c3xlC2okQHXZn/hctEq8cahurng0CkLbZCp+9VrPGNO8NcMaFS4Jo6r7OJ7bWgdhbVfTaTmeJek/dJnTPIZebWPzd5iY9sZR4/wgWia0EDAgKFaHF6W0zz8voborn1UY=,iv:tDSgjnqy2UjoKuyfQJLwNY44ApUrUT1RdR2V1FpY6HY=,tag:mh7WX3uxtkrupLK5CjL/JA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
