---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app jellyfin
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    # - name: intel-gpu-plugin
    #   namespace: default
    # - name: node-feature-discovery
    #   namespace: default
    - name: longhorn
      namespace: longhorn-system
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: 10.8.7@sha256:e309605c9f9c1fd3810da6159185f2bea96a161341c81af9b4731e43be3d9bb1
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        type: LoadBalancer
        externalIPs: ["${SVC_JELLYFIN_ADDR}"]
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8096
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Jellyfin"
          hajimari.io/icon: "television-classic"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "jellyfin-tls"
    podSecurityContext:
      fsGroup: 0
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 50Gi
        storageClass: longhorn-retain
        # labels:
        #   snapshot.home.arpa/enabled: "true"
    persistence:
      media:
        enabled: true
        type: nfs
        server: "scorpion.${SECRET_PRIVATE_DOMAIN}"
        path: /volume1/data/media
        mountPath: /media
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: feature.node.kubernetes.io/custom-intel-gpu
    #               operator: In
    #               values:
    #                 - "true"
    resources:
      requests:
        # gpu.intel.com/i915: 1
        cpu: 1000m
        memory: 2000Mi
      limits:
        # gpu.intel.com/i915: 1
        memory: 16000Mi
